### ISSUE TITLE
Assalamualaikum

### ISSUE THREAD

**Issue by ERLANRAHMAT** [justpiple/nextjs-personal-web#1]
Assalamualaikum mas ben api kamu kenapa ko di matiin?
😔 Padhal gw user zeks semenjak api mu ngga ada gw coba ngebuild api biar mirip kaya apimu dan ya aga mirip and lumayan ngobatin rindu gw ke zeks.me aa

**Comment by justpiple** [comment]
waalaikumsalam, API nya sengaja gw matiin karna uda ga keurus sering bgt eror, lagian uda banyak jg yg gantiin

btw thanks yaa uda pake zeks

**Comment by ERLANRAHMAT** [comment]
> waalaikumsalam, API nya sengaja gw matiin karna uda ga keurus sering bgt eror, lagian uda banyak jg yg gantiin
> 
> btw thanks yaa uda pake zeks

Yah gitu ya yaudha gapapa cuma rindu aja gitu sama apinya wkwkwk

Sama² juga and terimakasih udah sedian api zekz yg limitnya banyak

**Comment by justpiple** [comment]
sama sama
